name: build

on:
  push:
    branches: [ "d3d9-dev" ]
  pull_request:
    branches: [ "d3d9-dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: sudo apt-get install python3 python3-pip python3-setuptools python3-wheel ninja-build
    - name: off
      run: pip3 install meson
#    - name: pparere
#      run: chmod +x package-release.sh
#    - name: aaa
#      run: ./package-release.sh release build --no-package
    - name: build
      run: meson --cross-file build-win32.txt --buildtype release --prefix build/dxup-release/ build.w32
      
    - uses: actions/upload-artifact@v3
      with:
       name: "dxup-${CI_COMMIT_REF_NAME}.${CI_COMMIT_SHA}"
       path: build/dxup-release # or path/to/artifact
